version: '3'
services:
  frontend:
    build:
      context: ./business-loan-application
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./business-loan-backend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
